
<h3>Two Approaches to Handling Errors with Fetch</h3>
<p>Consistently managing fetch errors typically takes choosing one of two strategies. Converting runtime errors into http errors or throwing on http errors.</p>

<h4>Strategy 1: Converting Runtime Errors to HTTP Responses</h4>

<div class="language-js highlighter-rouge">
<div class="highlight">
<pre class="highlight" precode>
<code precode>async function tryFetchCatch(){
    try {
        return await fetch(...arguments);
    } catch(e) {
        return new Response(null, {status: 500, statusText: e.message});
    }
}</code></pre>
</div>
</div>

<p>
	Returning a <code>Response</code> on error (Strategy 1) is useful when you want to catch runtime errors and handle them like HTTP errors. This keeps your error handling uniform and makes it easier to deal with errors in the same way, regardless of their origin (HTTP status or network issue).
</p>

<h4>Strategy 2: Throwing on HTTP Errors</h4>

<div class="language-js highlighter-rouge">
<div class="highlight">
<pre class="highlight" precode>
<code precode>async function fetchThrow(){
   const res = await fetch(...arguments);
   if(!res.ok){
     throw new Error(`${res.status} ${res.statusText}`.trim());
   }
   return res;
}</code></pre>
</div>
</div>

<p>
	Throwing on HTTP errors (Strategy 2) is often useful when you want to ensure that only successful requests (i.e., HTTP status 200â€“299) are processed. Any other response is treated as an error and thrown, forcing the calling code to handle it.
</p>
<p>
	Many developers end up writing error handling logic twice (once for HTTP errors and again for network/runtime errors). With these strategies, you can centralize error handling, making it easier to ensure all errors are properly dealt with. Both strategies make code more concise and prevent repetitive if <code>res.ok</code> checks or <code>catch</code> blocks scattered throughout the application.
</p>
